### ISSUE TITLE
Unable to test on Basic Functionality using REST API

### ISSUE THREAD

**Issue by vimalkumar010** [cuba-platform/restapi#101]
Hi…
I’ve added the Rest API addon successfully… When i tried to invoke the Rest API thru the Postman. I’m getting the following error… Please help me to resolve the issue…
### Environment

- Platform version: 7.2.3 
- Addon version: 7.2.0
![Screenshot from 2020-04-24 19-23-03](https://user-images.githubusercontent.com/34364161/80210021-9b16c100-8665-11ea-92d5-4886d3819b1c.png)
 

- Client type: 
- Browser: 
- Database: 
- Operating system: 

### Description of the bug or enhancement

- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by EduardMan** [comment]
Hello
I decided this problem by creating a new role with a scope REST and gave permissions for working with REST. And, of course I added this Role to user who I want to use for working with REST API. For better understending I attached a screenshot. I suppose that they should add this information to their instruction because this thing is disapointing
![2020-05-21_08-42-24](https://user-images.githubusercontent.com/5735110/82527432-1a04f980-9b3f-11ea-874f-805ec4084cb1.png)
