### ISSUE TITLE
Character datatype isn't supported on filter operation

### ISSUE THREAD

**Issue by karandashovrz** [cuba-platform/restapi#134]
Need to add supporting of caharcter datatype on filter operation with next options:
'=', 'in', 'notIn', '<>', 'notEmpty'

**Comment by artemglinov** [comment]
### QA Notes

To test the fix, one needs to:
1) create an entity (e.g., `NewEntity`);
2) add an attribute of type `Char` (in the designer) which is actually of `Character` datatype (called, e.g.,`charAttr`);
3) create an entity instance (instances) with specific value (values) of `charAttr`;
4) send a GET or POST filter request as described in [docs](https://doc.cuba-platform.com/restapi-7.1/#rest_api_v2_ex_search_filter). It is possible to find an example of a suitable GET request parameter "filter" value in `entitiesFilterCharAttribute.json` file as well as `EntitiesControllerFT#loadEntitiesWithCharAttributeFilter` test in `restapi-demo` project.

In order to determine `"operator"` value refer to `RestFilterParser#findOperator` method.
